name: CDK deploy DEV
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy machine spraak streaming api to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials for dev
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install AWS CDK
        run: 'npm install -g aws-cdk'

      - name: Install Requirements 
        run: 'pip3 install -r requirements.txt'
        working-directory: cdk

      - name: Deploy stack to dev
        run: cdk deploy --require-approval never -c env=dev
        working-directory: cdk
